version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /cdnet
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"

  - package-ecosystem: gomod
    directory: /cli
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"

  - package-ecosystem: gomod
    directory: /cloud
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"

  - package-ecosystem: gomod
    directory: /cmd
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"

  - package-ecosystem: gomod
    directory: /core
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"

  - package-ecosystem: gomod
    directory: /linter
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"

  - package-ecosystem: gomod
    directory: /platform
    commit-message:
      prefix: ":arrow_up:"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*docker*"
